#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate / sync a README.md next to every tracked SKILL.md.
#
# The README is boilerplate derived from the skill's frontmatter (name +
# description) and its path (which is also its APM install id). The generated
# content lives between marker comments so any hand-written prose outside the
# block survives a re-sync.
#
#   ruby scripts/gen-skill-readme.rb           # write / update all READMEs
#   ruby scripts/gen-skill-readme.rb --check    # verify up-to-date (CI); no writes
#
# Exit codes: 0 = ok / all up-to-date, 1 = drift found (in --check mode).

require "open3"
require "yaml"

BEGIN_MARKER = "<!-- apm:readme:begin (generated by scripts/gen-skill-readme.rb — do not edit this block) -->"
END_MARKER = "<!-- apm:readme:end -->"
APM_NAMESPACE = "mizchi/skills"

def repo_root
  stdout, status = Open3.capture2("git", "rev-parse", "--show-toplevel")
  raise "not a git repository" unless status.success?

  stdout.strip
end

# Tracked SKILL.md files, excluding test/example fixtures. Mirrors the
# tracked-files contract used by validate-skill-frontmatter.rb.
def tracked_skill_dirs(root)
  stdout, status = Open3.capture2(
    "git", "-C", root, "ls-files", "-z", "--", ":(glob)**/SKILL.md"
  )
  raise "git ls-files failed" unless status.success?

  stdout.split("\0").reject(&:empty?)
        .reject { |p| p.include?("/examples/") }
        .map { |p| File.dirname(p) }
        .sort
end

def frontmatter(skill_md_path)
  text = File.read(skill_md_path)
  unless text.start_with?("---\n")
    raise "#{skill_md_path}: missing frontmatter"
  end

  closing = text.index("\n---", 4)
  raise "#{skill_md_path}: unterminated frontmatter" unless closing

  YAML.safe_load(text[4...closing])
end

def generated_block(name, description, apm_id)
  desc = description.to_s.strip.gsub(/\s*\n\s*/, " ")
  <<~MARKDOWN.rstrip
    #{BEGIN_MARKER}
    # #{name}

    > #{desc}

    ## Install

    ### APM (recommended)

    ```bash
    apm install #{apm_id}
    ```

    Or declare it in `apm.yml` for a reproducible setup:

    ```yaml
    dependencies:
      apm:
        - #{apm_id}
    ```

    then run `apm install`.

    ### Any agentskills.io-compatible agent

    This is an [Agent Skills](https://agentskills.io) skill — a portable
    `SKILL.md` folder that works with Claude Code, Codex, opencode, Gemini CLI,
    Cursor, and other [compatible agents](https://agentskills.io/clients).

    With the [`skills`](https://github.com/vercel-labs/skills) CLI (installs into
    every detected agent's skills directory):

    ```bash
    npx skills add mizchi/skills --skill #{name}
    ```

    Or copy the folder in directly:

    ```bash
    npx degit #{apm_id} ~/.claude/skills/#{name}
    ```

    See [SKILL.md](./SKILL.md) for what this skill does and when to use it.
    #{END_MARKER}
  MARKDOWN
end

# Splice the generated block into existing content, preserving anything
# outside the markers. A README with no markers gets the block prepended.
def render(existing, block)
  return "#{block}\n" if existing.nil? || existing.strip.empty?

  if existing.include?(BEGIN_MARKER) && existing.include?(END_MARKER)
    pre = existing[0...existing.index(BEGIN_MARKER)]
    post = existing[(existing.index(END_MARKER) + END_MARKER.length)..]
    "#{pre}#{block}#{post}"
  else
    "#{block}\n\n#{existing.lstrip}"
  end
end

check_mode = ARGV.include?("--check")
root = repo_root
drift = []
skipped = []

tracked_skill_dirs(root).each do |dir|
  abs_dir = File.join(root, dir)
  begin
    fm = frontmatter(File.join(abs_dir, "SKILL.md"))
  rescue StandardError, Psych::SyntaxError => e
    # Don't crash the whole sync on one malformed SKILL.md — the frontmatter
    # validator already gates on this. Surface it and move on.
    skipped << "#{dir}/SKILL.md (#{e.message.split("\n").first})"
    next
  end
  name = fm["name"] || File.basename(dir)
  apm_id = "#{APM_NAMESPACE}/#{dir}"

  readme_path = File.join(abs_dir, "README.md")
  existing = File.exist?(readme_path) ? File.read(readme_path) : nil
  rendered = render(existing, generated_block(name, fm["description"], apm_id))

  next if existing == rendered

  if check_mode
    drift << File.join(dir, "README.md")
  else
    File.write(readme_path, rendered)
    puts "synced #{dir}/README.md"
  end
end

skipped.each { |s| warn "skipped (unparseable frontmatter): #{s}" }

if check_mode
  if drift.empty?
    puts "all skill READMEs up to date"
  else
    warn "skill READMEs out of date (run `pkf run gen:readme`):"
    drift.each { |p| warn "  #{p}" }
    exit 1
  end
else
  puts "done"
end
